<a href="https://colab.research.google.com/github/ProfAndersonVanin/FATEC_MINERACAO_DADOS_2SEM2024/blob/main/Aula01_Demonstra%C3%A7%C3%A3o_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Demonstração da Biblioteca Numpy**

# Importação da Biblioteca

In [1]:
import numpy as np

# Gerar alguns dados aleatórios

Gerar um ndarray 2x3 - duas listas com 3 elementos

lista1 = [1,2,3]

lista2 = [4,5,6]

In [2]:
dados = np.random.rand(2,3)

In [3]:
dados

array([[0.43312687, 0.69002727, 0.02799975],
       [0.26368656, 0.68120291, 0.50186432]])

# Verificando o tipo do Array

In [4]:
dados.dtype

dtype('float64')

# Verificar Tamanho e Quantidade de Dimensões

In [5]:
dados.shape

(2, 3)

In [6]:
dados.ndim

2

# Criando um ndarray a partir de uma estrutura básica python - Ex. Listas

In [7]:
lista = [1,2,3,4,5]

In [8]:
dados1 = np.array(lista)

In [9]:
dados1

array([1, 2, 3, 4, 5])

In [10]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
dados2 = np.array(lista2)

In [12]:
dados2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Transfomando tipos

In [14]:
dados3 = np.array([[1,2,3],[4,5,6]])
dados3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
dados3_novo = dados3.astype(np.float64)
dados3_novo

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
dados3.dtype

dtype('int64')

In [17]:
dados3_novo.dtype

dtype('float64')

# Aritmética com Arrays

In [18]:
dados4 = np.array([[1,2,3],[4,5,6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
dados5 = np.array([[7,8,9],[10,11,12]])
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [27]:
dados5[1,1]

11

In [22]:
resultado = dados4 * dados5
resultado

array([[ 7, 16, 27],
       [40, 55, 72]])

# Indexação

In [24]:
exemplo = [1,2,3,4,5]
exemplo[2]

3

In [25]:
dadosseq = np.array([1,2,3,4,5,6])
dadosseq

array([1, 2, 3, 4, 5, 6])

In [26]:
dadosseq[4]

5

# Fatias

In [28]:
dadosseq[2:4]

array([3, 4])

In [29]:
x = dadosseq[2:4]

In [30]:
x

array([3, 4])

In [31]:
dadosseq

array([1, 2, 3, 4, 5, 6])

# Alterando um valor dentro de um nparray

In [32]:
dadosseq[2] = 11111
dadosseq

array([    1,     2, 11111,     4,     5,     6])

# Máscaras

In [37]:
fatia = dadosseq[2:4]
fatia
fatia[fatia < 10] = 50
fatia

array([11111,    50])

In [38]:
dadosseq

array([   50,    50, 11111,    50,     5,     6])

# Transposição

In [39]:
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
dados5.T

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [41]:
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
transposta = dados5.T


In [43]:
transposta

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

# Multiplicação de Matrizes com dots

In [44]:
np.dot(dados5,transposta)

array([[194, 266],
       [266, 365]])